### ISSUE TITLE
Header and footer support

### ISSUE THREAD

**Issue by hokster7** [paweldudek/carousel-collection-view-layout#2]
Hi,  I've got a (horizontal ;) use-case which lets the user scroll, scroll scroll to the end, and then there's a transition into a special end page. I was thinking this could be neatly implemented as a footer but was devastated to find that this view layout doesn't support headers and footers like flow layout does.

I'll probably hack up a custom CollectionViewFlowLayout solution for this, but I thought I'd leave a note here anyway. :)

**Comment by paweldudek** [comment]
Adding header and footer views shouldn't be that hard, however I'm a bit worried how this should behave. Should they center just like cells do? If so what should be their size (as they'd have to have size bigger or equal to cells to center correctly)? If they have size smaller than cells should additional offset be added? 

My personal preference is to leave them uncentered, aka if the layout detects that proposed resting position is near the header/footer just use that value. 

What do you think?

**Comment by hokster7** [comment]
@paweldudek I think now normally this is done is to provide delegate hooks, like `collectionViewLayout:referenceSizeForHeader` or some such. The header should be centred along the scroll axis (x-axis). Their default size is, say, `(100, collectionView.height)`.

**Comment by paweldudek** [comment]
@fatuhoku took me a while, but I've added header support in 1.1.0. Let me know whether this is what you've been looking for.

**Comment by paweldudek** [comment]
This has been implemented in 1.1.0.
